### ISSUE TITLE
Catching "Error: Missing authentication tokens"

### ISSUE THREAD

**Issue by wlaurance** [jfromaniello/passport-hawk#5]
I know that I am not sending the proper tokens. I am trying to define my app's behavior when requests do not include Hawk credentials.

Do you know of a good way to catch this error? The error is uncaught and express is returning a 500 (as its supposed too).

Is there a canonical way with this library, or with passport to handle this? ie send back a 401.

I know a few different ways to solve my issue, but I am wondering if there is a common pattern that I am not seeing.

Thanks

**Comment by jfromaniello** [comment]
v1.0.0 uses `fail` instead of `error` and this simplify things.

I've been using this for a year because I had the change in a branch
