### ISSUE TITLE
Implementer options are not passed to hawk

### ISSUE THREAD

**Issue by jamiemjennings** [jfromaniello/passport-hawk#9]
Passport allows for options to be passed in the `authenticate()` call to the implementing library.

Hawk provides options for the implementer to specify the request hostname and port to be used for hmac calculation. See:
https://www.npmjs.com/package/hawk#host-header-forgery

This is especially useful when using a reverse proxy in front of the node server, where the requesting client may make a request on a different protocol (https vs. http) and port (443 vs. 80 or custom port) to the proxy server vs. the server running node.

The passport-hawk implementation does not pass the specified options to the hawk library.

**Comment by jfromaniello** [comment]
closed in #9
